# Deploys code updates to my personal site on push to the master branch

name: Deploy on Push
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build and Deploy
      run: mvn install -B -s $GITHUB_WORKSPACE/settings.xml -PautoInstallBundle -Dsling.protocol=https -Dsling.port=443 -Dsling.host=$DEPLOY_HOST -Dsling.username=$DEPLOY_USERNAME -Dsling.password=$DEPLOY_PASSWORD
